version: '3'

services:
  # Ваш Node.js сайт
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MY_IP=localhost
      - CODESPACE_NAME
      - GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN
    depends_on:
      - documentserver
    volumes:
      - ./uploads:/app/uploads # Чтобы файлы не исчезали

  # Сервер ONLYOFFICE
  documentserver:
    image: onlyoffice/documentserver
    environment:
      - JWT_ENABLED=false
    ports:
      - "8080:80"
    restart: always
