version: '3'

services:
  # Node.js application service
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MY_IP=localhost
      # Pass special environment variables for dynamic URL construction in remote environments
      - CODESPACE_NAME=${CODESPACE_NAME}
      - GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN=${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
      # Explicitly define the document server URL for docker-compose environment
      - DOCUMENT_SERVER_URL=http://documentserver
    depends_on:
      - documentserver
    volumes:
      - ./uploads:/app/uploads # Чтобы файлы не исчезали

  # Сервер ONLYOFFICE
  documentserver:
    image: onlyoffice/documentserver
    environment:
      - JWT_ENABLED=false
    ports:
      - "8080:80"
    restart: always
